// GENERATED from the original place file's StarterGui/DataLoss — every serialized,
// scriptable property is reproduced verbatim so the rendered tree matches the
// original DataLoss ScreenGui exactly. Embedded LocalScripts are intentionally
// omitted here; their behaviour lives in src/client/uiClientBehaviors.client.ts.
// React owns the STRUCTURE only — translated game code mutates the mounted
// instances imperatively, exactly like the original operated on cloned templates.
/* eslint-disable */

import React from "@rbxts/react";

export function DataLossGui(): React.Element {
	return (
	React.createElement("ScreenGui", {
		Name: "DataLoss",
		AutoLocalize: true,
		ClipToDeviceSafeArea: true,
		DisplayOrder: 0,
		Enabled: false,
		ResetOnSpawn: true,
		SafeAreaCompatibility: Enum.SafeAreaCompatibility.FullscreenExtension,
		ScreenInsets: Enum.ScreenInsets.CoreUISafeInsets,
		SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
		SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
		SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
		SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
		SelectionGroup: false,
		ZIndexBehavior: Enum.ZIndexBehavior.Sibling,
	} as never, [
		React.createElement("Frame", {
			Name: "Frame",
			Active: false,
			AnchorPoint: new Vector2(0, 0),
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.X,
			BackgroundColor3: new Color3(0, 0, 0),
			BackgroundTransparency: 0.300000012,
			BorderColor3: new Color3(0.105882354, 0.164705887, 0.20784314),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 1,
			ClipsDescendants: false,
			Draggable: false,
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			Position: new UDim2(-0.0125000002, 0, 0.122930825, 0),
			Rotation: 0,
			Selectable: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(0.295631289, 0, 0.0816496611, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			Style: Enum.FrameStyle.Custom,
			Visible: false,
			ZIndex: 1,
		} as never, [
			React.createElement("TextLabel", {
				Name: "Title",
				Active: false,
				AnchorPoint: new Vector2(0, 0.5),
				AutoLocalize: true,
				AutomaticSize: Enum.AutomaticSize.None,
				BackgroundColor3: new Color3(1, 1, 1),
				BackgroundTransparency: 1,
				BorderColor3: new Color3(0.105882354, 0.164705887, 0.20784314),
				BorderMode: Enum.BorderMode.Outline,
				BorderSizePixel: 1,
				ClipsDescendants: false,
				Draggable: false,
				FontFace: new Font("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
				InputSink: Enum.InputSink.None,
				Interactable: true,
				LayoutOrder: 0,
				LineHeight: 1,
				MaxVisibleGraphemes: -1,
				OpenTypeFeatures: "",
				Position: new UDim2(0.221813574, 0, 0.204058528, 0),
				RichText: false,
				Rotation: 0,
				Selectable: false,
				SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
				SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
				SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
				SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
				SelectionGroup: false,
				SelectionOrder: 0,
				Size: new UDim2(0.267674655, 0, 0.445917666, 0),
				SizeConstraint: Enum.SizeConstraint.RelativeXY,
				Text: "ROBLOX",
				TextColor3: new Color3(1, 1, 1),
				TextDirection: Enum.TextDirection.Auto,
				TextScaled: true,
				TextSize: 14,
				TextStrokeColor3: new Color3(0, 0, 0),
				TextStrokeTransparency: 1,
				TextTransparency: 0,
				TextTruncate: Enum.TextTruncate.None,
				TextWrapped: true,
				TextXAlignment: Enum.TextXAlignment.Left,
				TextYAlignment: Enum.TextYAlignment.Center,
				Visible: true,
				ZIndex: 1,
			} as never),
			React.createElement("ImageLabel", {
				Name: "Title",
				Active: false,
				AnchorPoint: new Vector2(0, 0.5),
				AutoLocalize: true,
				AutomaticSize: Enum.AutomaticSize.None,
				BackgroundColor3: new Color3(1, 1, 1),
				BackgroundTransparency: 1,
				BorderColor3: new Color3(0.105882354, 0.164705887, 0.20784314),
				BorderMode: Enum.BorderMode.Outline,
				BorderSizePixel: 1,
				ClipsDescendants: false,
				Draggable: false,
				Image: "rbxassetid://8877073449",
				ImageColor3: new Color3(1, 1, 1),
				ImageRectOffset: new Vector2(0, 0),
				ImageRectSize: new Vector2(0, 0),
				ImageTransparency: 0,
				InputSink: Enum.InputSink.None,
				Interactable: true,
				LayoutOrder: 0,
				Position: new UDim2(0.0581682995, 0, 0.5, 0),
				ResampleMode: Enum.ResamplerMode.Default,
				Rotation: 0,
				ScaleType: Enum.ScaleType.Fit,
				Selectable: false,
				SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
				SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
				SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
				SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
				SelectionGroup: false,
				SelectionOrder: 0,
				Size: new UDim2(0.15043202, 0, 1, 0),
				SizeConstraint: Enum.SizeConstraint.RelativeXY,
				SliceCenter: new Rect(0, 0, 0, 0),
				SliceScale: 1,
				TileSize: new UDim2(1, 0, 1, 0),
				Visible: true,
				ZIndex: 1,
			} as never),
			React.createElement("TextLabel", {
				Name: "Title",
				Active: false,
				AnchorPoint: new Vector2(0, 0.5),
				AutoLocalize: true,
				AutomaticSize: Enum.AutomaticSize.None,
				BackgroundColor3: new Color3(1, 1, 1),
				BackgroundTransparency: 1,
				BorderColor3: new Color3(0.105882354, 0.164705887, 0.20784314),
				BorderMode: Enum.BorderMode.Outline,
				BorderSizePixel: 1,
				ClipsDescendants: false,
				Draggable: false,
				FontFace: new Font("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
				InputSink: Enum.InputSink.None,
				Interactable: true,
				LayoutOrder: 0,
				LineHeight: 1,
				MaxVisibleGraphemes: -1,
				OpenTypeFeatures: "",
				Position: new UDim2(0.219170958, 0, 0.704124212, 0),
				RichText: false,
				Rotation: 0,
				Selectable: false,
				SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
				SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
				SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
				SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
				SelectionGroup: false,
				SelectionOrder: 0,
				Size: new UDim2(0.557288647, 0, 0.591751397, 0),
				SizeConstraint: Enum.SizeConstraint.RelativeXY,
				Text: "Possible Data loss!",
				TextColor3: new Color3(1, 0, 0),
				TextDirection: Enum.TextDirection.Auto,
				TextScaled: true,
				TextSize: 14,
				TextStrokeColor3: new Color3(0, 0, 0),
				TextStrokeTransparency: 1,
				TextTransparency: 0,
				TextTruncate: Enum.TextTruncate.None,
				TextWrapped: true,
				TextXAlignment: Enum.TextXAlignment.Left,
				TextYAlignment: Enum.TextYAlignment.Center,
				Visible: true,
				ZIndex: 1,
			} as never),
			React.createElement("UIPadding", {
				Name: "UIPadding",
				PaddingBottom: new UDim(0.0500000007, 0),
				PaddingLeft: new UDim(0, 0),
				PaddingRight: new UDim(0, 0),
				PaddingTop: new UDim(0.0500000007, 0),
			} as never),
		]),
		React.createElement("Frame", {
			Name: "Frame",
			Active: false,
			AnchorPoint: new Vector2(0, 0),
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.X,
			BackgroundColor3: new Color3(0, 0, 0),
			BackgroundTransparency: 0.300000012,
			BorderColor3: new Color3(0.105882354, 0.164705887, 0.20784314),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 1,
			ClipsDescendants: false,
			Draggable: false,
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			Position: new UDim2(-0.0125000002, 0, 0.217375264, 0),
			Rotation: 0,
			Selectable: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(0.295631289, 0, 0.0816496611, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			Style: Enum.FrameStyle.Custom,
			Visible: false,
			ZIndex: 1,
		} as never, [
			React.createElement("UIPadding", {
				Name: "UIPadding",
				PaddingBottom: new UDim(0.0500000007, 0),
				PaddingLeft: new UDim(0, 0),
				PaddingRight: new UDim(0, 0),
				PaddingTop: new UDim(0.0500000007, 0),
			} as never),
			React.createElement("TextLabel", {
				Name: "Title",
				Active: false,
				AnchorPoint: new Vector2(0, 0.5),
				AutoLocalize: true,
				AutomaticSize: Enum.AutomaticSize.None,
				BackgroundColor3: new Color3(1, 1, 1),
				BackgroundTransparency: 1,
				BorderColor3: new Color3(0.105882354, 0.164705887, 0.20784314),
				BorderMode: Enum.BorderMode.Outline,
				BorderSizePixel: 1,
				ClipsDescendants: false,
				Draggable: false,
				FontFace: new Font("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
				InputSink: Enum.InputSink.None,
				Interactable: true,
				LayoutOrder: 0,
				LineHeight: 1,
				MaxVisibleGraphemes: -1,
				OpenTypeFeatures: "",
				Position: new UDim2(0.220013604, 0, 0.493712544, 0),
				RichText: false,
				Rotation: 0,
				Selectable: false,
				SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
				SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
				SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
				SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
				SelectionGroup: false,
				SelectionOrder: 0,
				Size: new UDim2(0.588318527, 0, 0.926943719, 0),
				SizeConstraint: Enum.SizeConstraint.RelativeXY,
				Text: "Contact Developer if missing items",
				TextColor3: new Color3(1, 1, 1),
				TextDirection: Enum.TextDirection.Auto,
				TextScaled: true,
				TextSize: 14,
				TextStrokeColor3: new Color3(0, 0, 0),
				TextStrokeTransparency: 1,
				TextTransparency: 0,
				TextTruncate: Enum.TextTruncate.None,
				TextWrapped: true,
				TextXAlignment: Enum.TextXAlignment.Left,
				TextYAlignment: Enum.TextYAlignment.Center,
				Visible: true,
				ZIndex: 1,
			} as never),
			React.createElement("ImageLabel", {
				Name: "Title",
				Active: false,
				AnchorPoint: new Vector2(0, 0.5),
				AutoLocalize: true,
				AutomaticSize: Enum.AutomaticSize.None,
				BackgroundColor3: new Color3(1, 1, 1),
				BackgroundTransparency: 1,
				BorderColor3: new Color3(0.105882354, 0.164705887, 0.20784314),
				BorderMode: Enum.BorderMode.Outline,
				BorderSizePixel: 1,
				ClipsDescendants: false,
				Draggable: false,
				Image: "rbxassetid://8877073449",
				ImageColor3: new Color3(1, 1, 1),
				ImageRectOffset: new Vector2(0, 0),
				ImageRectSize: new Vector2(0, 0),
				ImageTransparency: 0,
				InputSink: Enum.InputSink.None,
				Interactable: true,
				LayoutOrder: 0,
				Position: new UDim2(0.0555256531, 0, 0.481099606, 0),
				ResampleMode: Enum.ResamplerMode.Default,
				Rotation: 0,
				ScaleType: Enum.ScaleType.Fit,
				Selectable: false,
				SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
				SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
				SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
				SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
				SelectionGroup: false,
				SelectionOrder: 0,
				Size: new UDim2(0.15043202, 0, 1, 0),
				SizeConstraint: Enum.SizeConstraint.RelativeXY,
				SliceCenter: new Rect(0, 0, 0, 0),
				SliceScale: 1,
				TileSize: new UDim2(1, 0, 1, 0),
				Visible: true,
				ZIndex: 1,
			} as never),
		]),
	])
	);
}
