// GENERATED from the original place file's StarterGui/MobileInterface — every serialized,
// scriptable property is reproduced verbatim so the rendered tree matches the
// original MobileInterface ScreenGui exactly. Embedded LocalScripts are intentionally
// omitted here; their behaviour lives in src/client/uiClientBehaviors.client.ts.
// React owns the STRUCTURE only — translated game code mutates the mounted
// instances imperatively, exactly like the original operated on cloned templates.
//
// POST-LAUNCH ADDITION (hand-written, not from the place file): a fixed custom
// drive joystick on the left. VehicleKeyHandler.client.ts reads screen-space
// displacement directly, so steering never changes when the camera turns.
/* eslint-disable */

import React from "@rbxts/react";

export function MobileInterfaceGui(): React.Element {
	return (
	React.createElement("ScreenGui", {
		Name: "MobileInterface",
		AutoLocalize: true,
		ClipToDeviceSafeArea: true,
		DisplayOrder: 0,
		Enabled: false,
		ResetOnSpawn: true,
		SafeAreaCompatibility: Enum.SafeAreaCompatibility.FullscreenExtension,
		ScreenInsets: Enum.ScreenInsets.CoreUISafeInsets,
		SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
		SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
		SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
		SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
		SelectionGroup: false,
		ZIndexBehavior: Enum.ZIndexBehavior.Sibling,
	} as never, [
		React.createElement("UIPadding", {
			Name: "UIPadding",
			PaddingBottom: new UDim(0.0299999993, 0),
			PaddingLeft: new UDim(0.0199999996, 0),
			PaddingRight: new UDim(0.0199999996, 0),
			PaddingTop: new UDim(0.0299999993, 0),
		} as never),
		React.createElement("TextButton", {
			Name: "Boost",
			Active: true,
			AnchorPoint: new Vector2(1, 0.5),
			AutoButtonColor: true,
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.None,
			BackgroundColor3: new Color3(0.996078491, 0.149019614, 0),
			BackgroundTransparency: 0.400000006,
			BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 1,
			ClipsDescendants: false,
			Draggable: false,
			FontFace: new Font("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			LineHeight: 1,
			MaxVisibleGraphemes: -1,
			Modal: false,
			OpenTypeFeatures: "",
			Position: new UDim2(0.794216573, 0, 0.866450012, 0),
			RichText: false,
			Rotation: 0,
			Selectable: true,
			Selected: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(0.150000006, 0, 0.150000006, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			Style: Enum.ButtonStyle.Custom,
			Text: "",
			TextColor3: new Color3(0, 0, 0),
			TextDirection: Enum.TextDirection.Auto,
			TextScaled: false,
			TextSize: 14,
			TextStrokeColor3: new Color3(0, 0, 0),
			TextStrokeTransparency: 1,
			TextTransparency: 0,
			TextTruncate: Enum.TextTruncate.None,
			TextWrapped: false,
			TextXAlignment: Enum.TextXAlignment.Center,
			TextYAlignment: Enum.TextYAlignment.Center,
			Visible: true,
			ZIndex: 1,
		} as never, [
			React.createElement("UIAspectRatioConstraint", {
				Name: "UIAspectRatioConstraint",
				AspectRatio: 1,
				AspectType: Enum.AspectType.FitWithinMaxSize,
				DominantAxis: Enum.DominantAxis.Width,
			} as never),
			React.createElement("UICorner", {
				Name: "UICorner",
				BottomLeftRadius: new UDim(1, 0),
				BottomRightRadius: new UDim(1, 0),
				TopLeftRadius: new UDim(1, 0),
				TopRightRadius: new UDim(1, 0),
			} as never),
			React.createElement("UIStroke", {
				Name: "UIStroke",
				ApplyStrokeMode: Enum.ApplyStrokeMode.Border,
				BorderOffset: new UDim(0, 0),
				BorderStrokePosition: Enum.BorderStrokePosition.Outer,
				Color: new Color3(0.694117665, 0.694117665, 0.694117665),
				Enabled: true,
				LineJoinMode: Enum.LineJoinMode.Round,
				StrokeSizingMode: Enum.StrokeSizingMode.FixedSize,
				Thickness: 3,
				Transparency: 0,
				ZIndex: 1,
			} as never),
			React.createElement("ImageLabel", {
				Name: "ImageLabel",
				Active: false,
				AnchorPoint: new Vector2(0.5, 0.5),
				AutoLocalize: true,
				AutomaticSize: Enum.AutomaticSize.None,
				BackgroundColor3: new Color3(1, 1, 1),
				BackgroundTransparency: 1,
				BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
				BorderMode: Enum.BorderMode.Outline,
				BorderSizePixel: 1,
				ClipsDescendants: false,
				Draggable: false,
				Image: "http://www.roblox.com/asset/?id=6034684949",
				ImageColor3: new Color3(1, 1, 1),
				ImageRectOffset: new Vector2(0, 0),
				ImageRectSize: new Vector2(0, 0),
				ImageTransparency: 0,
				InputSink: Enum.InputSink.None,
				Interactable: true,
				LayoutOrder: 0,
				Position: new UDim2(0.5, 0, 0.5, 0),
				ResampleMode: Enum.ResamplerMode.Default,
				Rotation: 0,
				ScaleType: Enum.ScaleType.Stretch,
				Selectable: false,
				SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
				SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
				SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
				SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
				SelectionGroup: false,
				SelectionOrder: 0,
				Size: new UDim2(0.800000012, 0, 0.800000012, 0),
				SizeConstraint: Enum.SizeConstraint.RelativeXY,
				SliceCenter: new Rect(0, 0, 0, 0),
				SliceScale: 1,
				TileSize: new UDim2(1, 0, 1, 0),
				Visible: true,
				ZIndex: 1,
			} as never, [
				React.createElement("UIAspectRatioConstraint", {
					Name: "UIAspectRatioConstraint",
					AspectRatio: 1,
					AspectType: Enum.AspectType.FitWithinMaxSize,
					DominantAxis: Enum.DominantAxis.Width,
				} as never),
			]),
		]),
		React.createElement("TextButton", {
			Name: "Jump",
			Active: true,
			AnchorPoint: new Vector2(1, 0.5),
			AutoButtonColor: true,
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.None,
			BackgroundColor3: new Color3(0, 0.831372619, 0.192156881),
			BackgroundTransparency: 0.400000006,
			BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 1,
			ClipsDescendants: false,
			Draggable: false,
			FontFace: new Font("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			LineHeight: 1,
			MaxVisibleGraphemes: -1,
			Modal: false,
			OpenTypeFeatures: "",
			Position: new UDim2(0.794199288, 0, 0.564519346, 0),
			RichText: false,
			Rotation: 0,
			Selectable: true,
			Selected: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(0.150000006, 0, 0.150000006, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			Style: Enum.ButtonStyle.Custom,
			Text: "",
			TextColor3: new Color3(0, 0, 0),
			TextDirection: Enum.TextDirection.Auto,
			TextScaled: false,
			TextSize: 14,
			TextStrokeColor3: new Color3(0, 0, 0),
			TextStrokeTransparency: 1,
			TextTransparency: 0,
			TextTruncate: Enum.TextTruncate.None,
			TextWrapped: false,
			TextXAlignment: Enum.TextXAlignment.Center,
			TextYAlignment: Enum.TextYAlignment.Center,
			Visible: true,
			ZIndex: 1,
		} as never, [
			React.createElement("UIAspectRatioConstraint", {
				Name: "UIAspectRatioConstraint",
				AspectRatio: 1,
				AspectType: Enum.AspectType.FitWithinMaxSize,
				DominantAxis: Enum.DominantAxis.Width,
			} as never),
			React.createElement("UICorner", {
				Name: "UICorner",
				BottomLeftRadius: new UDim(1, 0),
				BottomRightRadius: new UDim(1, 0),
				TopLeftRadius: new UDim(1, 0),
				TopRightRadius: new UDim(1, 0),
			} as never),
			React.createElement("UIStroke", {
				Name: "UIStroke",
				ApplyStrokeMode: Enum.ApplyStrokeMode.Border,
				BorderOffset: new UDim(0, 0),
				BorderStrokePosition: Enum.BorderStrokePosition.Outer,
				Color: new Color3(0.694117665, 0.694117665, 0.694117665),
				Enabled: true,
				LineJoinMode: Enum.LineJoinMode.Round,
				StrokeSizingMode: Enum.StrokeSizingMode.FixedSize,
				Thickness: 3,
				Transparency: 0,
				ZIndex: 1,
			} as never),
			React.createElement("ImageLabel", {
				Name: "ImageLabel",
				Active: false,
				AnchorPoint: new Vector2(0.5, 0.5),
				AutoLocalize: true,
				AutomaticSize: Enum.AutomaticSize.None,
				BackgroundColor3: new Color3(1, 1, 1),
				BackgroundTransparency: 1,
				BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
				BorderMode: Enum.BorderMode.Outline,
				BorderSizePixel: 1,
				ClipsDescendants: false,
				Draggable: false,
				Image: "http://www.roblox.com/asset/?id=6031094674",
				ImageColor3: new Color3(1, 1, 1),
				ImageRectOffset: new Vector2(0, 0),
				ImageRectSize: new Vector2(0, 0),
				ImageTransparency: 0,
				InputSink: Enum.InputSink.None,
				Interactable: true,
				LayoutOrder: 0,
				Position: new UDim2(0.5, 0, 0.5, 0),
				ResampleMode: Enum.ResamplerMode.Default,
				Rotation: -90,
				ScaleType: Enum.ScaleType.Stretch,
				Selectable: false,
				SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
				SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
				SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
				SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
				SelectionGroup: false,
				SelectionOrder: 0,
				Size: new UDim2(0.800000012, 0, 0.800000012, 0),
				SizeConstraint: Enum.SizeConstraint.RelativeXY,
				SliceCenter: new Rect(0, 0, 0, 0),
				SliceScale: 1,
				TileSize: new UDim2(1, 0, 1, 0),
				Visible: true,
				ZIndex: 1,
			} as never, [
				React.createElement("UIAspectRatioConstraint", {
					Name: "UIAspectRatioConstraint",
					AspectRatio: 1,
					AspectType: Enum.AspectType.FitWithinMaxSize,
					DominantAxis: Enum.DominantAxis.Width,
				} as never),
			]),
		]),
		React.createElement("TextButton", {
			Name: "Drift",
			Active: true,
			AnchorPoint: new Vector2(1, 0.5),
			AutoButtonColor: true,
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.None,
			BackgroundColor3: new Color3(0.21960786, 0.235294133, 0.24313727),
			BackgroundTransparency: 0.400000006,
			BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 1,
			ClipsDescendants: false,
			Draggable: false,
			FontFace: new Font("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			LineHeight: 1,
			MaxVisibleGraphemes: -1,
			Modal: false,
			OpenTypeFeatures: "",
			Position: new UDim2(0.958261728, 0, 0.564519346, 0),
			RichText: false,
			Rotation: 0,
			Selectable: true,
			Selected: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(0.150000006, 0, 0.150000006, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			Style: Enum.ButtonStyle.Custom,
			Text: "",
			TextColor3: new Color3(0, 0, 0),
			TextDirection: Enum.TextDirection.Auto,
			TextScaled: false,
			TextSize: 14,
			TextStrokeColor3: new Color3(0, 0, 0),
			TextStrokeTransparency: 1,
			TextTransparency: 0,
			TextTruncate: Enum.TextTruncate.None,
			TextWrapped: false,
			TextXAlignment: Enum.TextXAlignment.Center,
			TextYAlignment: Enum.TextYAlignment.Center,
			Visible: true,
			ZIndex: 1,
		} as never, [
			React.createElement("UIAspectRatioConstraint", {
				Name: "UIAspectRatioConstraint",
				AspectRatio: 1,
				AspectType: Enum.AspectType.FitWithinMaxSize,
				DominantAxis: Enum.DominantAxis.Width,
			} as never),
			React.createElement("UICorner", {
				Name: "UICorner",
				BottomLeftRadius: new UDim(1, 0),
				BottomRightRadius: new UDim(1, 0),
				TopLeftRadius: new UDim(1, 0),
				TopRightRadius: new UDim(1, 0),
			} as never),
			React.createElement("UIStroke", {
				Name: "UIStroke",
				ApplyStrokeMode: Enum.ApplyStrokeMode.Border,
				BorderOffset: new UDim(0, 0),
				BorderStrokePosition: Enum.BorderStrokePosition.Outer,
				Color: new Color3(0.694117665, 0.694117665, 0.694117665),
				Enabled: true,
				LineJoinMode: Enum.LineJoinMode.Round,
				StrokeSizingMode: Enum.StrokeSizingMode.FixedSize,
				Thickness: 3,
				Transparency: 0,
				ZIndex: 1,
			} as never),
			React.createElement("ImageLabel", {
				Name: "ImageLabel",
				Active: false,
				AnchorPoint: new Vector2(0.5, 0.5),
				AutoLocalize: true,
				AutomaticSize: Enum.AutomaticSize.None,
				BackgroundColor3: new Color3(1, 1, 1),
				BackgroundTransparency: 1,
				BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
				BorderMode: Enum.BorderMode.Outline,
				BorderSizePixel: 1,
				ClipsDescendants: false,
				Draggable: false,
				Image: "http://www.roblox.com/asset/?id=8836384840",
				ImageColor3: new Color3(1, 1, 1),
				ImageRectOffset: new Vector2(0, 0),
				ImageRectSize: new Vector2(0, 0),
				ImageTransparency: 0,
				InputSink: Enum.InputSink.None,
				Interactable: true,
				LayoutOrder: 0,
				Position: new UDim2(0.5, 0, 0.5, 0),
				ResampleMode: Enum.ResamplerMode.Default,
				Rotation: 0,
				ScaleType: Enum.ScaleType.Stretch,
				Selectable: false,
				SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
				SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
				SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
				SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
				SelectionGroup: false,
				SelectionOrder: 0,
				Size: new UDim2(0.800000012, 0, 0.800000012, 0),
				SizeConstraint: Enum.SizeConstraint.RelativeXY,
				SliceCenter: new Rect(0, 0, 0, 0),
				SliceScale: 1,
				TileSize: new UDim2(1, 0, 1, 0),
				Visible: true,
				ZIndex: 1,
			} as never, [
				React.createElement("UIAspectRatioConstraint", {
					Name: "UIAspectRatioConstraint",
					AspectRatio: 1,
					AspectType: Enum.AspectType.FitWithinMaxSize,
					DominantAxis: Enum.DominantAxis.Width,
				} as never),
			]),
		]),
		// Fixed screen-space analog stick: X is steering and -Y is throttle.
		React.createElement("ImageButton", {
			Name: "DriveJoystick",
			Active: true,
			AnchorPoint: new Vector2(0, 1),
			AutoButtonColor: false,
			BackgroundColor3: new Color3(0.105882362, 0.117647059, 0.129411765),
			BackgroundTransparency: 0.35,
			BorderSizePixel: 0,
			Image: "",
			InputSink: Enum.InputSink.All,
			Position: new UDim2(0.015, 0, 0.985, 0),
			Selectable: false,
			Size: new UDim2(0.28, 0, 0.48, 0),
			Visible: true,
			ZIndex: 1,
		} as never, [
			React.createElement("UIAspectRatioConstraint", {
				Name: "UIAspectRatioConstraint",
				AspectRatio: 1,
				AspectType: Enum.AspectType.FitWithinMaxSize,
				DominantAxis: Enum.DominantAxis.Width,
			} as never),
			React.createElement("UICorner", {
				Name: "UICorner",
				CornerRadius: new UDim(1, 0),
			} as never),
			React.createElement("UIStroke", {
				Name: "UIStroke",
				Color: new Color3(0.694117665, 0.694117665, 0.694117665),
				Thickness: 3,
				Transparency: 0.15,
			} as never),
			React.createElement("Frame", {
				Name: "Knob",
				Active: false,
				AnchorPoint: new Vector2(0.5, 0.5),
				BackgroundColor3: new Color3(0.92, 0.92, 0.92),
				BackgroundTransparency: 0.18,
				BorderSizePixel: 0,
				Position: new UDim2(0.5, 0, 0.5, 0),
				Size: new UDim2(0.42, 0, 0.42, 0),
				ZIndex: 2,
			} as never, [
				React.createElement("UICorner", {
					Name: "UICorner",
					CornerRadius: new UDim(1, 0),
				} as never),
				React.createElement("UIStroke", {
					Name: "UIStroke",
					Color: new Color3(1, 1, 1),
					Thickness: 2,
					Transparency: 0.35,
				} as never),
			]),
		]),
	])
	);
}
