// GENERATED from the original place file's StarterGui/CrateMenu — every serialized,
// scriptable property is reproduced verbatim so the rendered tree matches the
// original CrateMenu ScreenGui exactly. Embedded LocalScripts are intentionally
// omitted here; their behaviour lives in src/client/uiClientBehaviors.client.ts.
// React owns the STRUCTURE only — translated game code mutates the mounted
// instances imperatively, exactly like the original operated on cloned templates.
/* eslint-disable */

import React from "@rbxts/react";

export function CrateMenuGui(): React.Element {
	return (
	React.createElement("ScreenGui", {
		Name: "CrateMenu",
		AutoLocalize: true,
		ClipToDeviceSafeArea: true,
		DisplayOrder: 0,
		Enabled: false,
		// Phase 5: client-mounted once by bootstrap.client.ts — ResetOnSpawn
		// must be false or the engine destroys it on respawn (original: true).
		ResetOnSpawn: false,
		SafeAreaCompatibility: Enum.SafeAreaCompatibility.FullscreenExtension,
		ScreenInsets: Enum.ScreenInsets.CoreUISafeInsets,
		SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
		SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
		SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
		SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
		SelectionGroup: false,
		ZIndexBehavior: Enum.ZIndexBehavior.Sibling,
	} as never, [
		React.createElement("Frame", {
			Name: "Background",
			Active: false,
			AnchorPoint: new Vector2(0, 0),
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.X,
			BackgroundColor3: new Color3(0.301960796, 0.10980393, 0.0627451017),
			BackgroundTransparency: 0,
			BorderColor3: new Color3(0.105882354, 0.164705887, 0.20784314),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 1,
			ClipsDescendants: false,
			Draggable: false,
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			Position: new UDim2(-1.00312746, 0, -1.01805556, 0),
			Rotation: 0,
			Selectable: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(5, 0, 5, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			Style: Enum.FrameStyle.Custom,
			Visible: true,
			ZIndex: -1,
		} as never, [
			React.createElement("UIGradient", {
				Name: "UIGradient",
				Color: new ColorSequence([new ColorSequenceKeypoint(0, new Color3(0, 0, 0)), new ColorSequenceKeypoint(0.108153, new Color3(0, 0, 0)), new ColorSequenceKeypoint(0.31614, new Color3(1, 1, 1)), new ColorSequenceKeypoint(0.43594, new Color3(0, 0, 0)), new ColorSequenceKeypoint(1, new Color3(0, 0, 0))]),
				Enabled: true,
				Offset: new Vector2(0, 0),
				Rotation: 0,
				Scale: 1,
				TileMode: Enum.GradientTileMode.Clamp,
				Transparency: new NumberSequence([new NumberSequenceKeypoint(0, 0, 0), new NumberSequenceKeypoint(0.0998852, 1, 0), new NumberSequenceKeypoint(0.27899, 0, 0), new NumberSequenceKeypoint(0.322618, 0, 0), new NumberSequenceKeypoint(0.500574, 0.98125, 0), new NumberSequenceKeypoint(1, 0, 0)]),
				Type: Enum.GradientType.Linear,
			} as never),
		]),
		React.createElement("ImageLabel", {
			Name: "pickerFrame",
			Active: false,
			AnchorPoint: new Vector2(0.5, 0.5),
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.None,
			BackgroundColor3: new Color3(1, 1, 1),
			BackgroundTransparency: 1,
			BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 1,
			ClipsDescendants: false,
			Draggable: false,
			Image: "rbxassetid://9770265344",
			ImageColor3: new Color3(1, 0.800000072, 0),
			ImageRectOffset: new Vector2(0, 0),
			ImageRectSize: new Vector2(0, 0),
			ImageTransparency: 0,
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			Position: new UDim2(0.499609083, 0, 0.5, 0),
			ResampleMode: Enum.ResamplerMode.Default,
			Rotation: 0,
			ScaleType: Enum.ScaleType.Stretch,
			Selectable: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(0.349999994, 0, 0.200000003, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			SliceCenter: new Rect(0, 0, 0, 0),
			SliceScale: 1,
			TileSize: new UDim2(1, 0, 1, 0),
			Visible: true,
			ZIndex: 3,
		} as never),
		React.createElement("TextLabel", {
			Name: "picker",
			Active: false,
			AnchorPoint: new Vector2(0.5, 0.5),
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.None,
			BackgroundColor3: new Color3(1, 1, 1),
			BackgroundTransparency: 1,
			BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 1,
			ClipsDescendants: false,
			Draggable: false,
			FontFace: new Font("rbxasset://fonts/families/FredokaOne.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			LineHeight: 1,
			MaxVisibleGraphemes: -1,
			OpenTypeFeatures: "",
			Position: new UDim2(0.145315111, 0, 0.471631736, 0),
			RichText: false,
			Rotation: 0,
			Selectable: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(0.290903926, 0, 0.133351669, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			Text: "OPENING",
			TextColor3: new Color3(1, 0.784313798, 0),
			TextDirection: Enum.TextDirection.Auto,
			TextScaled: true,
			TextSize: 8,
			TextStrokeColor3: new Color3(1, 1, 1),
			TextStrokeTransparency: 1,
			TextTransparency: 0.610000014,
			TextTruncate: Enum.TextTruncate.None,
			TextWrapped: true,
			TextXAlignment: Enum.TextXAlignment.Right,
			TextYAlignment: Enum.TextYAlignment.Center,
			Visible: true,
			ZIndex: 1,
		} as never),
		React.createElement("TextLabel", {
			Name: "picker",
			Active: false,
			AnchorPoint: new Vector2(0.5, 0.5),
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.None,
			BackgroundColor3: new Color3(1, 1, 1),
			BackgroundTransparency: 1,
			BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 1,
			ClipsDescendants: false,
			Draggable: false,
			FontFace: new Font("rbxasset://fonts/families/FredokaOne.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			LineHeight: 1,
			MaxVisibleGraphemes: -1,
			OpenTypeFeatures: "",
			Position: new UDim2(0.159779534, 0, 0.548650861, 0),
			RichText: false,
			Rotation: 0,
			Selectable: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(0.261975139, 0, 0.0567976162, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			Text: "CRATE - BASIC",
			TextColor3: new Color3(1, 1, 1),
			TextDirection: Enum.TextDirection.Auto,
			TextScaled: true,
			TextSize: 8,
			TextStrokeColor3: new Color3(0, 0, 0),
			TextStrokeTransparency: 1,
			TextTransparency: 0,
			TextTruncate: Enum.TextTruncate.None,
			TextWrapped: true,
			TextXAlignment: Enum.TextXAlignment.Right,
			TextYAlignment: Enum.TextYAlignment.Center,
			Visible: true,
			ZIndex: 1,
		} as never),
		React.createElement("ImageLabel", {
			Name: "pickerWhite",
			Active: false,
			AnchorPoint: new Vector2(0.5, 0.5),
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.None,
			BackgroundColor3: new Color3(1, 1, 1),
			BackgroundTransparency: 1,
			BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 1,
			ClipsDescendants: false,
			Draggable: false,
			Image: "rbxassetid://9770446044",
			ImageColor3: new Color3(1, 1, 1),
			ImageRectOffset: new Vector2(0, 0),
			ImageRectSize: new Vector2(0, 0),
			ImageTransparency: 0,
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			Position: new UDim2(0.499609083, 0, 0.5, 0),
			ResampleMode: Enum.ResamplerMode.Default,
			Rotation: 0,
			ScaleType: Enum.ScaleType.Stretch,
			Selectable: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(0.349999994, 0, 0.200000003, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			SliceCenter: new Rect(0, 0, 0, 0),
			SliceScale: 2,
			TileSize: new UDim2(1, 0, 1, 0),
			Visible: true,
			ZIndex: 4,
		} as never),
		React.createElement("Folder", {
			Name: "ItemText",
		} as never, [
			React.createElement("TextLabel", {
				Name: "Rarity",
				Active: false,
				AnchorPoint: new Vector2(0.5, 0.5),
				AutoLocalize: true,
				AutomaticSize: Enum.AutomaticSize.None,
				BackgroundColor3: new Color3(1, 1, 1),
				BackgroundTransparency: 1,
				BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
				BorderMode: Enum.BorderMode.Outline,
				BorderSizePixel: 1,
				ClipsDescendants: false,
				Draggable: false,
				FontFace: new Font("rbxasset://fonts/families/FredokaOne.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
				InputSink: Enum.InputSink.None,
				Interactable: true,
				LayoutOrder: 0,
				LineHeight: 1,
				MaxVisibleGraphemes: -1,
				OpenTypeFeatures: "",
				Position: new UDim2(0.838624179, 0, 0.472326189, 0),
				RichText: false,
				Rotation: 0,
				Selectable: false,
				SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
				SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
				SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
				SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
				SelectionGroup: false,
				SelectionOrder: 0,
				Size: new UDim2(0.291203588, 0, 0.0652961209, 0),
				SizeConstraint: Enum.SizeConstraint.RelativeXY,
				Text: "COMMON",
				TextColor3: new Color3(0, 1, 0.0823529437),
				TextDirection: Enum.TextDirection.Auto,
				TextScaled: true,
				TextSize: 8,
				TextStrokeColor3: new Color3(1, 1, 1),
				TextStrokeTransparency: 0,
				TextTransparency: 0,
				TextTruncate: Enum.TextTruncate.None,
				TextWrapped: true,
				TextXAlignment: Enum.TextXAlignment.Left,
				TextYAlignment: Enum.TextYAlignment.Center,
				Visible: true,
				ZIndex: 1,
			} as never),
			React.createElement("TextLabel", {
				Name: "NameType",
				Active: false,
				AnchorPoint: new Vector2(0.5, 0.5),
				AutoLocalize: true,
				AutomaticSize: Enum.AutomaticSize.None,
				BackgroundColor3: new Color3(1, 1, 1),
				BackgroundTransparency: 1,
				BorderColor3: new Color3(0.105882362, 0.164705887, 0.207843155),
				BorderMode: Enum.BorderMode.Outline,
				BorderSizePixel: 1,
				ClipsDescendants: false,
				Draggable: false,
				FontFace: new Font("rbxasset://fonts/families/FredokaOne.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
				InputSink: Enum.InputSink.None,
				Interactable: true,
				LayoutOrder: 0,
				LineHeight: 1,
				MaxVisibleGraphemes: -1,
				OpenTypeFeatures: "",
				Position: new UDim2(0.823837638, 0, 0.527811348, 0),
				RichText: false,
				Rotation: 0,
				Selectable: false,
				SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
				SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
				SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
				SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
				SelectionGroup: false,
				SelectionOrder: 0,
				Size: new UDim2(0.261630625, 0, 0.045674257, 0),
				SizeConstraint: Enum.SizeConstraint.RelativeXY,
				Text: "Silver Metalic - Paint",
				TextColor3: new Color3(1, 1, 1),
				TextDirection: Enum.TextDirection.Auto,
				TextScaled: true,
				TextSize: 8,
				TextStrokeColor3: new Color3(0, 0, 0),
				TextStrokeTransparency: 1,
				TextTransparency: 0,
				TextTruncate: Enum.TextTruncate.None,
				TextWrapped: true,
				TextXAlignment: Enum.TextXAlignment.Left,
				TextYAlignment: Enum.TextYAlignment.Center,
				Visible: true,
				ZIndex: 1,
			} as never),
		]),
		React.createElement("Frame", {
			Name: "Frame",
			Active: false,
			AnchorPoint: new Vector2(0.5, 1),
			AutoLocalize: true,
			AutomaticSize: Enum.AutomaticSize.None,
			BackgroundColor3: new Color3(1, 1, 1),
			BackgroundTransparency: 0.899999976,
			BorderColor3: new Color3(0, 0, 0),
			BorderMode: Enum.BorderMode.Outline,
			BorderSizePixel: 0,
			ClipsDescendants: false,
			Draggable: false,
			InputSink: Enum.InputSink.None,
			Interactable: true,
			LayoutOrder: 0,
			Position: new UDim2(0.5, 0, 10, 0),
			Rotation: 0,
			Selectable: false,
			SelectionBehaviorDown: Enum.SelectionBehavior.Escape,
			SelectionBehaviorLeft: Enum.SelectionBehavior.Escape,
			SelectionBehaviorRight: Enum.SelectionBehavior.Escape,
			SelectionBehaviorUp: Enum.SelectionBehavior.Escape,
			SelectionGroup: false,
			SelectionOrder: 0,
			Size: new UDim2(0.180000007, 0, 10, 0),
			SizeConstraint: Enum.SizeConstraint.RelativeXY,
			Style: Enum.FrameStyle.Custom,
			Visible: true,
			ZIndex: 1,
		} as never, [
			React.createElement("UIStroke", {
				Name: "UIStroke",
				ApplyStrokeMode: Enum.ApplyStrokeMode.Contextual,
				BorderOffset: new UDim(0, 0),
				BorderStrokePosition: Enum.BorderStrokePosition.Outer,
				Color: new Color3(1, 0.701960802, 0),
				Enabled: true,
				LineJoinMode: Enum.LineJoinMode.Round,
				StrokeSizingMode: Enum.StrokeSizingMode.FixedSize,
				Thickness: 10,
				Transparency: 0.600000024,
				ZIndex: 1,
			} as never),
			React.createElement("UIGridLayout", {
				Name: "UIGridLayout",
				CellPadding: new UDim2(0, 5, 0, 0),
				CellSize: new UDim2(1, 0, 0.0250000004, 0),
				FillDirection: Enum.FillDirection.Horizontal,
				FillDirectionMaxCells: 0,
				HorizontalAlignment: Enum.HorizontalAlignment.Left,
				SortOrder: Enum.SortOrder.LayoutOrder,
				StartCorner: Enum.StartCorner.TopLeft,
				VerticalAlignment: Enum.VerticalAlignment.Top,
			} as never),
			React.createElement("UIPadding", {
				Name: "UIPadding",
				PaddingBottom: new UDim(0, 0),
				PaddingLeft: new UDim(0, 5),
				PaddingRight: new UDim(0, 5),
				PaddingTop: new UDim(0, 0),
			} as never),
		]),
		React.createElement("Sound", {
			Name: "click",
			AcousticSimulationEnabled: true,
			LoopRegion: new NumberRange(0, 60000),
			Looped: false,
			PlayOnRemove: false,
			PlaybackRegion: new NumberRange(0, 60000),
			PlaybackRegionsEnabled: false,
			PlaybackSpeed: 1,
			Playing: false,
			RollOffMaxDistance: 10000,
			RollOffMinDistance: 10,
			RollOffMode: Enum.RollOffMode.Inverse,
			SoundId: "rbxassetid://421058925",
			TimePosition: 0,
			Volume: 0.5,
		} as never),
		React.createElement("Sound", {
			Name: "CompletionSound",
			AcousticSimulationEnabled: true,
			LoopRegion: new NumberRange(0, 60000),
			Looped: false,
			PlayOnRemove: false,
			PlaybackRegion: new NumberRange(0, 60000),
			PlaybackRegionsEnabled: false,
			PlaybackSpeed: 2,
			Playing: false,
			RollOffMaxDistance: 30,
			RollOffMinDistance: 10,
			RollOffMode: Enum.RollOffMode.Inverse,
			SoundId: "rbxassetid://1525651753",
			TimePosition: 0.5,
			Volume: 0.300000012,
		} as never, [
			React.createElement("ReverbSoundEffect", {
				Name: "ReverbSoundEffect",
				DecayTime: 1.5,
				Density: 1,
				Diffusion: 1,
				DryLevel: 0,
				Enabled: true,
				Priority: 0,
				WetLevel: -4,
			} as never),
		]),
	])
	);
}
